#!/usr/bin/env python3
"""Validate and render the XnnTransfer project semantic model."""

from __future__ import annotations

import argparse
import fnmatch
import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional, Sequence, Set, Tuple


ID = re.compile(r"^[A-Z][A-Z0-9-]+$")
PLAN_ID = re.compile(r"^DP-[A-Z0-9-]+$")
MODULE_ID = re.compile(r"^[a-z][a-z0-9_]*$")
CLASSIFICATIONS = {"preserve", "requalify", "replace", "remove"}
QUALIFICATIONS = {"current", "historical", "unqualified"}
BUDGET_STATUSES = {"active", "deferred"}
GENERATED_HEADER = "<!-- Generated by tool/harness/project_model.py; do not edit. -->"

BLUEPRINT_FIELDS = {
    "schema_version",
    "id",
    "title",
    "mission",
    "state_order",
    "goals",
    "milestones",
    "capabilities",
    "outcomes",
}
GOAL_FIELDS = {"id", "title", "statement", "milestones"}
MILESTONE_FIELDS = {"id", "title", "sequence", "outcomes"}
CAPABILITY_FIELDS = {"id", "title", "depends_on", "implementation_units"}
OUTCOME_FIELDS = {
    "id",
    "title",
    "milestone",
    "capability",
    "statement",
    "depends_on",
    "invariants",
    "criteria",
    "target_state",
    "deferred_reason",
}
DEPENDENCY_FIELDS = {"outcome", "minimum_state"}
CRITERION_FIELDS = {"id", "statement", "negative_definitions"}
INVARIANTS_FIELDS = {"schema_version", "invariants"}
INVARIANT_FIELDS = {
    "id",
    "category",
    "statement",
    "decision_refs",
    "applies_to",
}
BASELINE_FIELDS = {"schema_version", "states"}
BASELINE_STATE_FIELDS = {"outcome", "state", "basis"}
QUALITY_FIELDS = {"schema_version", "budgets"}
BUDGET_FIELDS = {
    "id",
    "dimension",
    "statement",
    "outcomes",
    "metric",
    "operator",
    "threshold",
    "unit",
    "status",
    "gate",
    "deferred_reason",
}
ASSETS_FIELDS = {"schema_version", "production_roots", "units"}
UNIT_FIELDS = {
    "id",
    "title",
    "capabilities",
    "architecture_modules",
    "production_paths",
    "test_paths",
    "classification",
    "qualification",
    "evidence",
    "rationale",
    "follow_up_outcomes",
}
CHANGE_FIELDS = {
    "schema_version",
    "id",
    "title",
    "depends_on",
    "transitions",
}
TRANSITION_FIELDS = {
    "plan",
    "plan_revision",
    "outcome",
    "outcome_revision",
    "from",
    "to",
    "criteria",
    "preserves",
    "requires",
}
REQUIRE_FIELDS = {
    "outcome",
    "outcome_revision",
    "minimum_state",
}


class ProjectModelError(RuntimeError):
    """Raised when the project semantic model is inconsistent."""


def _object_without_duplicates(pairs: Sequence[Tuple[str, Any]]) -> Dict[str, Any]:
    result: Dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ProjectModelError("duplicate JSON key: {}".format(key))
        result[key] = value
    return result


def load_json(path: Path) -> Dict[str, Any]:
    try:
        with path.open(encoding="utf-8") as source:
            value = json.load(source, object_pairs_hook=_object_without_duplicates)
    except (OSError, json.JSONDecodeError) as error:
        raise ProjectModelError("cannot read {}: {}".format(path, error)) from error
    if not isinstance(value, dict):
        raise ProjectModelError("{} must contain one JSON object".format(path))
    return value


def canonical_bytes(value: Any) -> bytes:
    try:
        return json.dumps(
            value,
            ensure_ascii=False,
            allow_nan=False,
            separators=(",", ":"),
            sort_keys=True,
        ).encode("utf-8")
    except (TypeError, ValueError) as error:
        raise ProjectModelError(
            "value is not canonical JSON: {}".format(error)
        ) from error


def canonical_sha256(value: Any) -> str:
    return hashlib.sha256(canonical_bytes(value)).hexdigest()


def plan_revision_sha256(plan: Mapping[str, Any]) -> str:
    return canonical_sha256(plan)


def _exact(value: Any, fields: Set[str], label: str) -> Dict[str, Any]:
    if not isinstance(value, dict):
        raise ProjectModelError("{} must be an object".format(label))
    missing = sorted(fields - set(value))
    extra = sorted(set(value) - fields)
    if missing or extra:
        raise ProjectModelError(
            "{} has invalid fields; missing={}, extra={}".format(label, missing, extra)
        )
    return value


def _string(value: Any, label: str) -> str:
    if not isinstance(value, str) or not value:
        raise ProjectModelError("{} must be a non-empty string".format(label))
    return value


def _identifier(value: Any, label: str, pattern: re.Pattern[str] = ID) -> str:
    result = _string(value, label)
    if pattern.fullmatch(result) is None:
        raise ProjectModelError("{} is invalid: {}".format(label, result))
    return result


def _strings(value: Any, label: str, allow_empty: bool = False) -> List[str]:
    if not isinstance(value, list) or (not value and not allow_empty):
        raise ProjectModelError("{} must be an array".format(label))
    result = [_string(item, "{} item".format(label)) for item in value]
    if len(result) != len(set(result)):
        raise ProjectModelError("{} contains duplicates".format(label))
    return result


def _relative_path(value: Any, label: str) -> str:
    result = _string(value, label).replace("\\", "/")
    path = Path(result)
    if (
        path.is_absolute()
        or ".." in path.parts
        or result == ".git"
        or result.startswith(".git/")
    ):
        raise ProjectModelError("{} is outside the repository".format(label))
    return result


def _unique_documents(
    values: Sequence[Mapping[str, Any]], label: str
) -> Dict[str, Mapping[str, Any]]:
    result: Dict[str, Mapping[str, Any]] = {}
    for index, value in enumerate(values):
        item_id = _identifier(value.get("id"), "{}[{}].id".format(label, index))
        if item_id in result:
            raise ProjectModelError("{} duplicates {}".format(label, item_id))
        result[item_id] = value
    return result


def _topological(graph: Mapping[str, Sequence[str]], label: str) -> List[str]:
    visiting: Set[str] = set()
    visited: Set[str] = set()
    order: List[str] = []

    def visit(node: str) -> None:
        if node in visiting:
            raise ProjectModelError("{} contains a cycle at {}".format(label, node))
        if node in visited:
            return
        if node not in graph:
            raise ProjectModelError("{} references unknown node {}".format(label, node))
        visiting.add(node)
        for dependency in graph[node]:
            visit(dependency)
        visiting.remove(node)
        visited.add(node)
        order.append(node)

    for node in sorted(graph):
        visit(node)
    return order


@dataclass(frozen=True)
class ProjectModel:
    root: Path
    blueprint: Mapping[str, Any]
    invariants: Mapping[str, Mapping[str, Any]]
    baseline: Mapping[str, str]
    baseline_basis: Mapping[str, str]
    quality_budgets: Mapping[str, Mapping[str, Any]]
    assets: Mapping[str, Mapping[str, Any]]
    changes: Mapping[str, Mapping[str, Any]]
    projected_states: Mapping[str, str]
    plan_changes: Mapping[str, str]
    architecture_modules: Mapping[str, Mapping[str, Any]]

    @property
    def outcomes(self) -> Mapping[str, Mapping[str, Any]]:
        return {item["id"]: item for item in self.blueprint["outcomes"]}

    @property
    def capabilities(self) -> Mapping[str, Mapping[str, Any]]:
        return {item["id"]: item for item in self.blueprint["capabilities"]}


def _validate_blueprint(
    value: Mapping[str, Any],
) -> Tuple[
    Dict[str, Mapping[str, Any]],
    Dict[str, Mapping[str, Any]],
    Dict[str, Mapping[str, Any]],
    Dict[str, Mapping[str, Any]],
    Tuple[str, ...],
]:
    blueprint = _exact(value, BLUEPRINT_FIELDS, "blueprint")
    if blueprint["schema_version"] != 1:
        raise ProjectModelError("blueprint schema_version must be 1")
    _identifier(blueprint["id"], "blueprint.id")
    _string(blueprint["title"], "blueprint.title")
    _string(blueprint["mission"], "blueprint.mission")
    states = tuple(_strings(blueprint["state_order"], "blueprint.state_order"))
    if len(states) < 2 or states[0] != "absent" or states[-1] != "qualified":
        raise ProjectModelError(
            "blueprint state_order must start at absent and end at qualified"
        )

    goals = _unique_documents(blueprint["goals"], "blueprint.goals")
    milestones = _unique_documents(blueprint["milestones"], "blueprint.milestones")
    capabilities = _unique_documents(
        blueprint["capabilities"], "blueprint.capabilities"
    )
    outcomes = _unique_documents(blueprint["outcomes"], "blueprint.outcomes")

    milestone_owners: Dict[str, str] = {}
    for goal_id, raw in goals.items():
        goal = _exact(raw, GOAL_FIELDS, "goal {}".format(goal_id))
        _string(goal["title"], "{}.title".format(goal_id))
        _string(goal["statement"], "{}.statement".format(goal_id))
        for milestone_id in _strings(
            goal["milestones"], "{}.milestones".format(goal_id)
        ):
            if milestone_id not in milestones:
                raise ProjectModelError(
                    "{} references unknown milestone {}".format(goal_id, milestone_id)
                )
            if milestone_id in milestone_owners:
                raise ProjectModelError(
                    "{} belongs to multiple goals".format(milestone_id)
                )
            milestone_owners[milestone_id] = goal_id
    missing_milestones = sorted(set(milestones) - set(milestone_owners))
    if missing_milestones:
        raise ProjectModelError(
            "milestones have no goal: {}".format(", ".join(missing_milestones))
        )

    milestone_outcomes: Dict[str, str] = {}
    sequences: Set[int] = set()
    for milestone_id, raw in milestones.items():
        milestone = _exact(raw, MILESTONE_FIELDS, "milestone {}".format(milestone_id))
        _string(milestone["title"], "{}.title".format(milestone_id))
        sequence = milestone["sequence"]
        if not isinstance(sequence, int) or isinstance(sequence, bool) or sequence < 0:
            raise ProjectModelError("{} sequence is invalid".format(milestone_id))
        if sequence in sequences:
            raise ProjectModelError(
                "milestone sequence {} is duplicated".format(sequence)
            )
        sequences.add(sequence)
        for outcome_id in _strings(
            milestone["outcomes"], "{}.outcomes".format(milestone_id)
        ):
            if outcome_id not in outcomes:
                raise ProjectModelError(
                    "{} references unknown outcome {}".format(milestone_id, outcome_id)
                )
            if outcome_id in milestone_outcomes:
                raise ProjectModelError(
                    "{} belongs to multiple milestones".format(outcome_id)
                )
            milestone_outcomes[outcome_id] = milestone_id
    missing_outcomes = sorted(set(outcomes) - set(milestone_outcomes))
    if missing_outcomes:
        raise ProjectModelError(
            "outcomes have no milestone: {}".format(", ".join(missing_outcomes))
        )

    capability_graph: Dict[str, Sequence[str]] = {}
    declared_units: Set[str] = set()
    for capability_id, raw in capabilities.items():
        capability = _exact(
            raw, CAPABILITY_FIELDS, "capability {}".format(capability_id)
        )
        _string(capability["title"], "{}.title".format(capability_id))
        capability_graph[capability_id] = _strings(
            capability["depends_on"],
            "{}.depends_on".format(capability_id),
            allow_empty=True,
        )
        units = _strings(
            capability["implementation_units"],
            "{}.implementation_units".format(capability_id),
        )
        declared_units.update(units)
    _topological(capability_graph, "capability graph")

    criterion_ids: Set[str] = set()
    outcome_graph: Dict[str, Sequence[str]] = {}
    for outcome_id, raw in outcomes.items():
        outcome = _exact(raw, OUTCOME_FIELDS, "outcome {}".format(outcome_id))
        _string(outcome["title"], "{}.title".format(outcome_id))
        _string(outcome["statement"], "{}.statement".format(outcome_id))
        if outcome["milestone"] != milestone_outcomes[outcome_id]:
            raise ProjectModelError(
                "{} milestone does not match milestone ownership".format(outcome_id)
            )
        if outcome["capability"] not in capabilities:
            raise ProjectModelError(
                "{} references unknown capability {}".format(
                    outcome_id, outcome["capability"]
                )
            )
        dependencies = outcome["depends_on"]
        if not isinstance(dependencies, list):
            raise ProjectModelError("{} depends_on must be an array".format(outcome_id))
        dependency_ids: List[str] = []
        for index, raw_dependency in enumerate(dependencies):
            dependency = _exact(
                raw_dependency,
                DEPENDENCY_FIELDS,
                "{}.depends_on[{}]".format(outcome_id, index),
            )
            dependency_id = _identifier(
                dependency["outcome"],
                "{} dependency outcome".format(outcome_id),
            )
            if dependency_id == outcome_id:
                raise ProjectModelError("{} depends on itself".format(outcome_id))
            if dependency["minimum_state"] not in states:
                raise ProjectModelError(
                    "{} dependency state is invalid".format(outcome_id)
                )
            dependency_ids.append(dependency_id)
        if len(dependency_ids) != len(set(dependency_ids)):
            raise ProjectModelError("{} dependencies are duplicated".format(outcome_id))
        outcome_graph[outcome_id] = dependency_ids
        _strings(outcome["invariants"], "{}.invariants".format(outcome_id))
        criteria = outcome["criteria"]
        if not isinstance(criteria, list) or not criteria:
            raise ProjectModelError("{} criteria must be non-empty".format(outcome_id))
        for index, raw_criterion in enumerate(criteria):
            criterion = _exact(
                raw_criterion,
                CRITERION_FIELDS,
                "{}.criteria[{}]".format(outcome_id, index),
            )
            criterion_id = _identifier(
                criterion["id"], "{} criterion id".format(outcome_id)
            )
            if criterion_id in criterion_ids:
                raise ProjectModelError(
                    "criterion {} belongs to multiple outcomes".format(criterion_id)
                )
            criterion_ids.add(criterion_id)
            _string(
                criterion["statement"],
                "{}.{}.statement".format(outcome_id, criterion_id),
            )
            _strings(
                criterion["negative_definitions"],
                "{}.{}.negative_definitions".format(outcome_id, criterion_id),
            )
        if outcome["target_state"] not in states:
            raise ProjectModelError("{} target_state is invalid".format(outcome_id))
        if outcome["deferred_reason"] is not None:
            _string(
                outcome["deferred_reason"],
                "{}.deferred_reason".format(outcome_id),
            )
    _topological(outcome_graph, "outcome graph")
    return goals, milestones, capabilities, outcomes, states


def _validate_invariants(
    value: Mapping[str, Any],
    outcomes: Mapping[str, Mapping[str, Any]],
    root: Path,
) -> Dict[str, Mapping[str, Any]]:
    document = _exact(value, INVARIANTS_FIELDS, "invariants")
    if document["schema_version"] != 1:
        raise ProjectModelError("invariants schema_version must be 1")
    invariants = _unique_documents(document["invariants"], "invariants")
    applies: Dict[str, Set[str]] = {outcome_id: set() for outcome_id in outcomes}
    for invariant_id, raw in invariants.items():
        invariant = _exact(raw, INVARIANT_FIELDS, "invariant {}".format(invariant_id))
        _string(invariant["category"], "{}.category".format(invariant_id))
        _string(invariant["statement"], "{}.statement".format(invariant_id))
        for path in _strings(
            invariant["decision_refs"], "{}.decision_refs".format(invariant_id)
        ):
            relative = _relative_path(path, "{} decision ref".format(invariant_id))
            if not (root / relative).is_file():
                raise ProjectModelError(
                    "{} decision ref is missing: {}".format(invariant_id, relative)
                )
        for outcome_id in _strings(
            invariant["applies_to"], "{}.applies_to".format(invariant_id)
        ):
            if outcome_id not in outcomes:
                raise ProjectModelError(
                    "{} references unknown outcome {}".format(invariant_id, outcome_id)
                )
            applies[outcome_id].add(invariant_id)
    for outcome_id, outcome in outcomes.items():
        declared = set(outcome["invariants"])
        unknown = sorted(declared - set(invariants))
        if unknown:
            raise ProjectModelError(
                "{} references unknown invariants: {}".format(
                    outcome_id, ", ".join(unknown)
                )
            )
        if declared != applies[outcome_id]:
            raise ProjectModelError(
                "{} invariant projection differs between Blueprint and invariant "
                "catalogue".format(outcome_id)
            )
    return invariants


def _validate_baseline(
    value: Mapping[str, Any],
    outcomes: Mapping[str, Mapping[str, Any]],
    states: Sequence[str],
) -> Tuple[Dict[str, str], Dict[str, str]]:
    document = _exact(value, BASELINE_FIELDS, "composition baseline")
    if document["schema_version"] != 1:
        raise ProjectModelError("composition baseline schema_version must be 1")
    raw_states = document["states"]
    if not isinstance(raw_states, list):
        raise ProjectModelError("composition baseline states must be an array")
    result: Dict[str, str] = {}
    basis: Dict[str, str] = {}
    for index, raw in enumerate(raw_states):
        item = _exact(raw, BASELINE_STATE_FIELDS, "baseline state {}".format(index))
        outcome_id = _identifier(item["outcome"], "baseline outcome")
        if outcome_id not in outcomes:
            raise ProjectModelError(
                "baseline references unknown outcome {}".format(outcome_id)
            )
        if outcome_id in result:
            raise ProjectModelError("baseline duplicates {}".format(outcome_id))
        if item["state"] not in states:
            raise ProjectModelError("{} baseline state is invalid".format(outcome_id))
        result[outcome_id] = item["state"]
        basis[outcome_id] = _string(item["basis"], "{} basis".format(outcome_id))
    if set(result) != set(outcomes):
        raise ProjectModelError(
            "baseline must cover every outcome exactly once; missing={}, extra={}".format(
                sorted(set(outcomes) - set(result)),
                sorted(set(result) - set(outcomes)),
            )
        )
    return result, basis


def _validate_quality(
    value: Mapping[str, Any],
    outcomes: Mapping[str, Mapping[str, Any]],
    gates: Set[str],
) -> Dict[str, Mapping[str, Any]]:
    document = _exact(value, QUALITY_FIELDS, "quality budgets")
    if document["schema_version"] != 1:
        raise ProjectModelError("quality budgets schema_version must be 1")
    budgets = _unique_documents(document["budgets"], "quality budgets")
    for budget_id, raw in budgets.items():
        budget = _exact(raw, BUDGET_FIELDS, "quality budget {}".format(budget_id))
        _string(budget["dimension"], "{}.dimension".format(budget_id))
        _string(budget["statement"], "{}.statement".format(budget_id))
        for outcome_id in _strings(budget["outcomes"], "{}.outcomes".format(budget_id)):
            if outcome_id not in outcomes:
                raise ProjectModelError(
                    "{} references unknown outcome {}".format(budget_id, outcome_id)
                )
        _string(budget["metric"], "{}.metric".format(budget_id))
        _string(budget["operator"], "{}.operator".format(budget_id))
        if budget["threshold"] is not None and (
            not isinstance(budget["threshold"], (int, float))
            or isinstance(budget["threshold"], bool)
        ):
            raise ProjectModelError("{} threshold is invalid".format(budget_id))
        _string(budget["unit"], "{}.unit".format(budget_id))
        if budget["status"] not in BUDGET_STATUSES:
            raise ProjectModelError("{} status is invalid".format(budget_id))
        if budget["status"] == "active":
            if budget["threshold"] is None:
                raise ProjectModelError(
                    "{} active budget requires a threshold".format(budget_id)
                )
            gate = _string(budget["gate"], "{}.gate".format(budget_id))
            if gate not in gates:
                raise ProjectModelError(
                    "{} references unknown gate {}".format(budget_id, gate)
                )
            if budget["deferred_reason"] is not None:
                raise ProjectModelError(
                    "{} active budget cannot have deferred_reason".format(budget_id)
                )
        else:
            if budget["gate"] is not None or budget["threshold"] is not None:
                raise ProjectModelError(
                    "{} deferred budget cannot claim a gate or threshold".format(
                        budget_id
                    )
                )
            _string(
                budget["deferred_reason"],
                "{}.deferred_reason".format(budget_id),
            )
    return budgets


def _validate_assets(
    value: Mapping[str, Any],
    root: Path,
    capabilities: Mapping[str, Mapping[str, Any]],
    outcomes: Mapping[str, Mapping[str, Any]],
    architecture_modules: Mapping[str, Mapping[str, Any]],
) -> Dict[str, Mapping[str, Any]]:
    document = _exact(value, ASSETS_FIELDS, "assets")
    if document["schema_version"] != 1:
        raise ProjectModelError("assets schema_version must be 1")
    production_roots = [
        _relative_path(path, "asset production root")
        for path in _strings(document["production_roots"], "asset production roots")
    ]
    units = _unique_documents(document["units"], "asset units")
    for unit_id, raw in units.items():
        unit = _exact(raw, UNIT_FIELDS, "asset unit {}".format(unit_id))
        _string(unit["title"], "{}.title".format(unit_id))
        for capability_id in _strings(
            unit["capabilities"], "{}.capabilities".format(unit_id)
        ):
            if capability_id not in capabilities:
                raise ProjectModelError(
                    "{} references unknown capability {}".format(unit_id, capability_id)
                )
        for module_id in _strings(
            unit["architecture_modules"],
            "{}.architecture_modules".format(unit_id),
            allow_empty=True,
        ):
            if module_id not in architecture_modules:
                raise ProjectModelError(
                    "{} references unknown architecture module {}".format(
                        unit_id, module_id
                    )
                )
        paths = [
            _relative_path(path, "{} production path".format(unit_id))
            for path in _strings(
                unit["production_paths"], "{}.production_paths".format(unit_id)
            )
        ]
        for path in _strings(
            unit["test_paths"], "{}.test_paths".format(unit_id), allow_empty=True
        ):
            _relative_path(path, "{} test path".format(unit_id))
        if unit["classification"] not in CLASSIFICATIONS:
            raise ProjectModelError("{} classification is invalid".format(unit_id))
        if unit["qualification"] not in QUALIFICATIONS:
            raise ProjectModelError("{} qualification is invalid".format(unit_id))
        _strings(unit["evidence"], "{}.evidence".format(unit_id))
        rationale = _string(unit["rationale"], "{}.rationale".format(unit_id))
        if len(rationale) < 20:
            raise ProjectModelError("{} rationale is too short".format(unit_id))
        for outcome_id in _strings(
            unit["follow_up_outcomes"], "{}.follow_up_outcomes".format(unit_id)
        ):
            if outcome_id not in outcomes:
                raise ProjectModelError(
                    "{} references unknown follow-up outcome {}".format(
                        unit_id, outcome_id
                    )
                )
        if (
            unit["classification"] in {"replace", "remove"}
            and not unit["follow_up_outcomes"]
        ):
            raise ProjectModelError(
                "{} destructive classification requires a follow-up outcome".format(
                    unit_id
                )
            )
        if not any(
            any(ch in path for ch in "*?[") or (root / path).exists() for path in paths
        ):
            raise ProjectModelError(
                "{} production paths do not exist or declare a glob".format(unit_id)
            )

    unit_capabilities: Dict[str, Set[str]] = {unit_id: set() for unit_id in units}
    for capability_id, capability in capabilities.items():
        for unit_id in capability["implementation_units"]:
            if unit_id not in units:
                raise ProjectModelError(
                    "{} references unknown implementation unit {}".format(
                        capability_id, unit_id
                    )
                )
            unit_capabilities[unit_id].add(capability_id)
    for unit_id, unit in units.items():
        if set(unit["capabilities"]) != unit_capabilities[unit_id]:
            raise ProjectModelError(
                "{} capability projection differs between Blueprint and assets".format(
                    unit_id
                )
            )

    production_files: List[str] = []
    for root_name in production_roots:
        root_path = root / root_name
        if not root_path.is_dir():
            raise ProjectModelError(
                "asset production root is missing: {}".format(root_name)
            )
        production_files.extend(
            path.relative_to(root).as_posix()
            for path in root_path.rglob("*")
            if path.is_file()
        )
    for path in sorted(production_files):
        owners = [
            unit_id
            for unit_id, unit in units.items()
            if any(
                fnmatch.fnmatchcase(path, pattern)
                for pattern in unit["production_paths"]
            )
        ]
        if len(owners) != 1:
            raise ProjectModelError(
                "production asset {} must have one unit owner; found {}".format(
                    path, owners
                )
            )
    return units


def _criterion_index(
    outcomes: Mapping[str, Mapping[str, Any]],
) -> Dict[str, Tuple[str, Mapping[str, Any]]]:
    return {
        criterion["id"]: (outcome_id, criterion)
        for outcome_id, outcome in outcomes.items()
        for criterion in outcome["criteria"]
    }


def _validate_plan_semantics(
    plan: Mapping[str, Any],
    criteria: Mapping[str, Tuple[str, Mapping[str, Any]]],
) -> Set[str]:
    result: Set[str] = set()
    for requirement in plan["requirements"]:
        for criterion in requirement["criteria"]:
            criterion_id = criterion["id"]
            if criterion_id not in criteria:
                raise ProjectModelError(
                    "{} criterion {} is absent from the Blueprint".format(
                        plan["id"], criterion_id
                    )
                )
            blueprint_criterion = criteria[criterion_id][1]
            if criterion["statement"] != blueprint_criterion["statement"]:
                raise ProjectModelError(
                    "{} weakens or changes Blueprint statement {}".format(
                        plan["id"], criterion_id
                    )
                )
            if (
                criterion["negative_definitions"]
                != blueprint_criterion["negative_definitions"]
            ):
                raise ProjectModelError(
                    "{} weakens or changes Blueprint negatives {}".format(
                        plan["id"], criterion_id
                    )
                )
            result.add(criterion_id)
    return result


def _validate_changes(
    changes: Mapping[str, Mapping[str, Any]],
    plans: Mapping[str, Mapping[str, Any]],
    outcomes: Mapping[str, Mapping[str, Any]],
    baseline: Mapping[str, str],
    states: Sequence[str],
    invariants: Mapping[str, Mapping[str, Any]],
) -> Tuple[Dict[str, str], Dict[str, str]]:
    graph: Dict[str, Sequence[str]] = {}
    for change_id, raw in changes.items():
        change = _exact(raw, CHANGE_FIELDS, "change {}".format(change_id))
        if change["schema_version"] != 1:
            raise ProjectModelError("{} schema_version must be 1".format(change_id))
        _string(change["title"], "{}.title".format(change_id))
        graph[change_id] = _strings(
            change["depends_on"], "{}.depends_on".format(change_id), allow_empty=True
        )
        if not isinstance(change["transitions"], list) or not change["transitions"]:
            raise ProjectModelError(
                "{} transitions must be non-empty".format(change_id)
            )
    order = _topological(graph, "Blueprint change graph")
    state_rank = {state: index for index, state in enumerate(states)}
    current = dict(baseline)
    criteria = _criterion_index(outcomes)
    plan_criteria = {
        plan_id: _validate_plan_semantics(plan, criteria)
        for plan_id, plan in plans.items()
    }
    plan_changes: Dict[str, str] = {}
    mapped_plan_criteria: Dict[str, Set[str]] = {plan_id: set() for plan_id in plans}
    outcome_writers: Set[Tuple[str, str]] = set()
    for change_id in order:
        change = changes[change_id]
        for index, raw_transition in enumerate(change["transitions"]):
            transition = _exact(
                raw_transition,
                TRANSITION_FIELDS,
                "{} transition {}".format(change_id, index),
            )
            plan_id = _identifier(
                transition["plan"], "{} transition plan".format(change_id), PLAN_ID
            )
            if plan_id not in plans:
                raise ProjectModelError(
                    "{} references unknown Plan {}".format(change_id, plan_id)
                )
            if plan_id in plan_changes and plan_changes[plan_id] != change_id:
                raise ProjectModelError(
                    "{} belongs to multiple Blueprint changes".format(plan_id)
                )
            plan_changes[plan_id] = change_id
            plan_revision = _string(
                transition["plan_revision"], "{} plan revision".format(change_id)
            )
            if plan_revision != plan_revision_sha256(plans[plan_id]):
                raise ProjectModelError(
                    "{} transition has stale Plan revision".format(plan_id)
                )
            outcome_id = _identifier(
                transition["outcome"], "{} transition outcome".format(change_id)
            )
            if outcome_id not in outcomes:
                raise ProjectModelError(
                    "{} references unknown outcome {}".format(change_id, outcome_id)
                )
            outcome = outcomes[outcome_id]
            if transition["outcome_revision"] != canonical_sha256(outcome):
                raise ProjectModelError(
                    "{} transition has stale outcome revision".format(outcome_id)
                )
            source = transition["from"]
            target = transition["to"]
            if source not in state_rank or target not in state_rank:
                raise ProjectModelError(
                    "{} transition state is invalid".format(outcome_id)
                )
            writer = (outcome_id, source)
            if writer in outcome_writers:
                raise ProjectModelError(
                    "{} has multiple writers from {}".format(outcome_id, source)
                )
            outcome_writers.add(writer)
            if current[outcome_id] != source:
                raise ProjectModelError(
                    "{} transition requires {}, found {}".format(
                        outcome_id, source, current[outcome_id]
                    )
                )
            if state_rank[target] <= state_rank[source]:
                raise ProjectModelError(
                    "{} transition does not advance state".format(outcome_id)
                )
            transition_criteria = set(
                _strings(
                    transition["criteria"],
                    "{} transition criteria".format(outcome_id),
                )
            )
            outcome_criteria = {criterion["id"] for criterion in outcome["criteria"]}
            if not transition_criteria <= outcome_criteria:
                raise ProjectModelError(
                    "{} transition claims foreign criteria".format(outcome_id)
                )
            if not transition_criteria <= plan_criteria[plan_id]:
                raise ProjectModelError(
                    "{} transition claims criteria outside {}".format(
                        outcome_id, plan_id
                    )
                )
            duplicate_criteria = mapped_plan_criteria[plan_id] & transition_criteria
            if duplicate_criteria:
                raise ProjectModelError(
                    "{} criteria are mapped more than once: {}".format(
                        plan_id, ", ".join(sorted(duplicate_criteria))
                    )
                )
            mapped_plan_criteria[plan_id].update(transition_criteria)
            preserves = set(
                _strings(
                    transition["preserves"],
                    "{} transition preserves".format(outcome_id),
                    allow_empty=True,
                )
            )
            if preserves != set(outcome["invariants"]):
                raise ProjectModelError(
                    "{} transition does not preserve every Blueprint invariant".format(
                        outcome_id
                    )
                )
            raw_requires = transition["requires"]
            if not isinstance(raw_requires, list):
                raise ProjectModelError(
                    "{} transition requires must be an array".format(outcome_id)
                )
            expected_requires = {
                dependency["outcome"]: dependency["minimum_state"]
                for dependency in outcome["depends_on"]
            }
            actual_requires: Dict[str, str] = {}
            for require_index, raw_require in enumerate(raw_requires):
                require = _exact(
                    raw_require,
                    REQUIRE_FIELDS,
                    "{} require {}".format(outcome_id, require_index),
                )
                required_id = _identifier(
                    require["outcome"], "{} required outcome".format(outcome_id)
                )
                if required_id not in outcomes:
                    raise ProjectModelError(
                        "{} requires unknown outcome {}".format(outcome_id, required_id)
                    )
                if required_id in actual_requires:
                    raise ProjectModelError(
                        "{} duplicates required outcome {}".format(
                            outcome_id, required_id
                        )
                    )
                if require["outcome_revision"] != canonical_sha256(
                    outcomes[required_id]
                ):
                    raise ProjectModelError(
                        "{} has stale required node revision {}".format(
                            outcome_id, required_id
                        )
                    )
                minimum = require["minimum_state"]
                if minimum not in state_rank:
                    raise ProjectModelError(
                        "{} requires invalid state".format(outcome_id)
                    )
                actual_requires[required_id] = minimum
                if state_rank[current[required_id]] < state_rank[minimum]:
                    raise ProjectModelError(
                        "{} precondition {} requires {}, found {}".format(
                            outcome_id,
                            required_id,
                            minimum,
                            current[required_id],
                        )
                    )
            if actual_requires != expected_requires:
                raise ProjectModelError(
                    "{} transition preconditions differ from Blueprint".format(
                        outcome_id
                    )
                )
            current[outcome_id] = target
    if set(plan_changes) != set(plans):
        raise ProjectModelError(
            "every Plan must belong to one Blueprint change; missing={}, extra={}".format(
                sorted(set(plans) - set(plan_changes)),
                sorted(set(plan_changes) - set(plans)),
            )
        )
    for plan_id in plans:
        if mapped_plan_criteria[plan_id] != plan_criteria[plan_id]:
            raise ProjectModelError(
                "{} criteria are not completely mapped to Blueprint transitions".format(
                    plan_id
                )
            )
    for outcome_id, outcome in outcomes.items():
        if (
            current[outcome_id] != outcome["target_state"]
            and outcome["deferred_reason"] is None
        ):
            raise ProjectModelError(
                "{} target is uncovered and not explicitly deferred".format(outcome_id)
            )
        if (
            current[outcome_id] == outcome["target_state"]
            and outcome["deferred_reason"] is not None
        ):
            raise ProjectModelError(
                "{} reaches target but remains marked deferred".format(outcome_id)
            )
    return current, plan_changes


def _project_source_documents(
    blueprint: Mapping[str, Any],
    invariant_document: Mapping[str, Any],
    baseline_document: Mapping[str, Any],
    quality_document: Mapping[str, Any],
    asset_document: Mapping[str, Any],
    changes: Mapping[str, Mapping[str, Any]],
) -> Mapping[str, Any]:
    return {
        "blueprint": blueprint,
        "invariants": invariant_document,
        "composition_baseline": baseline_document,
        "quality_budgets": quality_document,
        "assets": asset_document,
        "changes": {change_id: changes[change_id] for change_id in sorted(changes)},
    }


def load_project(
    root: Path,
    plans: Mapping[str, Mapping[str, Any]],
    gates: Set[str],
    architecture_modules: Mapping[str, Mapping[str, Any]],
) -> ProjectModel:
    root = root.resolve()
    project_root = root / ".agents" / "project"
    blueprint = load_json(project_root / "blueprint.json")
    invariant_document = load_json(project_root / "invariants.json")
    baseline_document = load_json(project_root / "composition-baseline.json")
    quality_document = load_json(project_root / "quality-budgets.json")
    asset_document = load_json(project_root / "assets.json")
    changes: Dict[str, Mapping[str, Any]] = {}
    for path in sorted((project_root / "changes").glob("BC-*.json")):
        change = load_json(path)
        change_id = _identifier(change.get("id"), "change id")
        if change_id in changes:
            raise ProjectModelError("duplicate Blueprint change {}".format(change_id))
        changes[change_id] = change
    if not changes:
        raise ProjectModelError("project model requires at least one Blueprint change")

    _, _, capabilities, outcomes, states = _validate_blueprint(blueprint)
    invariants = _validate_invariants(invariant_document, outcomes, root)
    baseline, baseline_basis = _validate_baseline(baseline_document, outcomes, states)
    quality = _validate_quality(quality_document, outcomes, gates)
    assets = _validate_assets(
        asset_document,
        root,
        capabilities,
        outcomes,
        architecture_modules,
    )
    projected, plan_changes = _validate_changes(
        changes,
        plans,
        outcomes,
        baseline,
        states,
        invariants,
    )
    return ProjectModel(
        root=root,
        blueprint=blueprint,
        invariants=invariants,
        baseline=baseline,
        baseline_basis=baseline_basis,
        quality_budgets=quality,
        assets=assets,
        changes=changes,
        projected_states=projected,
        plan_changes=plan_changes,
        architecture_modules=architecture_modules,
    )


def _plan_map(project: ProjectModel) -> Mapping[str, List[str]]:
    result: Dict[str, List[str]] = {outcome_id: [] for outcome_id in project.outcomes}
    for change in project.changes.values():
        for transition in change["transitions"]:
            if transition["plan"] not in result[transition["outcome"]]:
                result[transition["outcome"]].append(transition["plan"])
    return result


def render_roadmap(project: ProjectModel) -> str:
    plans = _plan_map(project)
    lines = [
        GENERATED_HEADER,
        "# Delivery Roadmap",
        "",
        "This is a deterministic Blueprint projection. Runtime task state is shown by",
        "`tool/harness/agent.sh list` and is never committed here.",
        "A checked item means its target is covered by the composition baseline or an",
        "accepted transition; it does not assert runtime delivery completion.",
        "",
    ]
    milestones = sorted(
        project.blueprint["milestones"], key=lambda item: item["sequence"]
    )
    for milestone in milestones:
        lines.extend(["## {}".format(milestone["title"]), ""])
        for outcome_id in milestone["outcomes"]:
            outcome = project.outcomes[outcome_id]
            projected = project.projected_states[outcome_id]
            target = outcome["target_state"]
            marker = "x" if projected == target else " "
            delivery = ", ".join(plans[outcome_id])
            if not delivery:
                if project.baseline[outcome_id] == target:
                    delivery = "composition baseline"
                else:
                    delivery = "deferred: {}".format(outcome["deferred_reason"])
            lines.extend(
                [
                    "- [{}] `{}` {}".format(marker, outcome_id, outcome["title"]),
                    "  - planned composition: `{}` -> `{}`".format(
                        project.baseline[outcome_id], projected
                    ),
                    "  - target: `{}`".format(target),
                    "  - delivery: {}".format(delivery),
                ]
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_capability_map(project: ProjectModel) -> str:
    lines = [
        GENERATED_HEADER,
        "# Capability Map",
        "",
        "Capabilities express the stable project decomposition. Delivery Plans bind",
        "outcome transitions; they do not define this hierarchy.",
        "",
    ]
    outcomes_by_capability: Dict[str, List[str]] = {
        capability_id: [] for capability_id in project.capabilities
    }
    for outcome_id, outcome in project.outcomes.items():
        outcomes_by_capability[outcome["capability"]].append(outcome_id)
    for capability in project.blueprint["capabilities"]:
        capability_id = capability["id"]
        lines.extend(
            [
                "## {} `{}`".format(capability["title"], capability_id),
                "",
                "- Depends on: {}".format(
                    ", ".join("`{}`".format(item) for item in capability["depends_on"])
                    or "none"
                ),
                "- Implementation units: {}".format(
                    ", ".join(
                        "`{}`".format(item)
                        for item in capability["implementation_units"]
                    )
                ),
                "- Outcomes: {}".format(
                    ", ".join(
                        "`{}`".format(item)
                        for item in outcomes_by_capability[capability_id]
                    )
                    or "none"
                ),
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def render_module_map(project: ProjectModel) -> str:
    lines = [
        GENERATED_HEADER,
        "# Module And Asset Map",
        "",
        "| Unit | Classification | Qualification | Architecture modules | Production paths |",
        "| --- | --- | --- | --- | --- |",
    ]
    for unit_id in sorted(project.assets):
        unit = project.assets[unit_id]
        modules = (
            ", ".join("`{}`".format(item) for item in unit["architecture_modules"])
            or "none"
        )
        paths = "<br>".join("`{}`".format(item) for item in unit["production_paths"])
        lines.append(
            "| `{}` | `{}` | `{}` | {} | {} |".format(
                unit_id,
                unit["classification"],
                unit["qualification"],
                modules,
                paths,
            )
        )
    lines.append("")
    return "\n".join(lines)


def render_semantic_baseline(project: ProjectModel) -> str:
    counts: Dict[str, int] = {classification: 0 for classification in CLASSIFICATIONS}
    for unit in project.assets.values():
        counts[unit["classification"]] += 1
    lines = [
        GENERATED_HEADER,
        "# Project Semantic Baseline",
        "",
        "## Asset Disposition",
        "",
        "| Classification | Count | Meaning |",
        "| --- | ---: | --- |",
        "| `preserve` | {} | Retain as an independent contract or currently qualified control-plane asset. |".format(
            counts["preserve"]
        ),
        "| `requalify` | {} | Keep the canonical implementation and obtain current Blueprint evidence. |".format(
            counts["requalify"]
        ),
        "| `replace` | {} | Rewrite the canonical implementation in place after defect evidence. |".format(
            counts["replace"]
        ),
        "| `remove` | {} | Delete an obsolete or duplicate asset after absence evidence. |".format(
            counts["remove"]
        ),
        "",
        "Accepted Git history is delivery input, not automatic current qualification.",
        "No product implementation is deleted by this baseline.",
        "",
        "## Ordered Requalification",
        "",
        "1. Protocol and core contracts",
        "2. Storage and identity",
        "3. TLS and session",
        "4. Transfer",
        "5. C ABI bridge",
        "6. Flutter application and presentation",
        "7. Cross-platform end-to-end qualification",
        "",
        "## Plan Composition",
        "",
        "| Plan | Blueprint change |",
        "| --- | --- |",
    ]
    for plan_id in sorted(project.plan_changes):
        lines.append("| `{}` | `{}` |".format(plan_id, project.plan_changes[plan_id]))
    lines.append("")
    return "\n".join(lines)


GENERATED_DOCUMENTS = {
    "docs/roadmap.md": render_roadmap,
    "docs/product/capability-map.md": render_capability_map,
    "docs/architecture/module-map.md": render_module_map,
    "docs/project/semantic-baseline.md": render_semantic_baseline,
}


def generated_documents(project: ProjectModel) -> Mapping[str, str]:
    return {path: renderer(project) for path, renderer in GENERATED_DOCUMENTS.items()}


def write_generated_documents(project: ProjectModel) -> None:
    for relative, content in generated_documents(project).items():
        path = project.root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def check_generated_documents(project: ProjectModel) -> None:
    for relative, expected in generated_documents(project).items():
        path = project.root / relative
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError as error:
            raise ProjectModelError(
                "generated document is missing: {}".format(relative)
            ) from error
        if actual != expected:
            raise ProjectModelError(
                "generated document is stale: {}; run project-model generate".format(
                    relative
                )
            )


def project_source_digest(root: Path) -> str:
    project_root = root.resolve() / ".agents" / "project"
    blueprint = load_json(project_root / "blueprint.json")
    invariant_document = load_json(project_root / "invariants.json")
    baseline_document = load_json(project_root / "composition-baseline.json")
    quality_document = load_json(project_root / "quality-budgets.json")
    asset_document = load_json(project_root / "assets.json")
    changes = {
        load_json(path)["id"]: load_json(path)
        for path in sorted((project_root / "changes").glob("BC-*.json"))
    }
    return canonical_sha256(
        _project_source_documents(
            blueprint,
            invariant_document,
            baseline_document,
            quality_document,
            asset_document,
            changes,
        )
    )


def _architecture_modules(root: Path) -> Dict[str, Mapping[str, Any]]:
    value = load_json(root / ".agents" / "architecture" / "modules.json")
    raw_modules = value.get("modules")
    if not isinstance(raw_modules, list):
        raise ProjectModelError("architecture module inventory is invalid")
    return {
        _identifier(item.get("id"), "architecture module id", MODULE_ID): item
        for item in raw_modules
        if isinstance(item, dict)
    }


def _plans(root: Path) -> Dict[str, Mapping[str, Any]]:
    result: Dict[str, Mapping[str, Any]] = {}
    for path in sorted((root / ".agents" / "plans").glob("DP-*.json")):
        value = load_json(path)
        plan_id = _identifier(value.get("id"), "Plan id", PLAN_ID)
        result[plan_id] = value
    return result


def _gates(root: Path) -> Set[str]:
    value = load_json(root / ".agents" / "gates.json")
    gates = value.get("gates")
    if not isinstance(gates, dict):
        raise ProjectModelError("Gate policy is invalid")
    return set(gates)


def load_repository_project(root: Path) -> ProjectModel:
    root = root.resolve()
    return load_project(
        root,
        _plans(root),
        _gates(root),
        _architecture_modules(root),
    )


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd())
    commands = parser.add_subparsers(dest="command", required=True)
    validate = commands.add_parser("validate")
    validate.add_argument("--check-docs", action="store_true")
    commands.add_parser("generate")
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = _parser()
    args = parser.parse_args(argv)
    root = args.root.resolve()
    try:
        project = load_repository_project(root)
        if args.command == "generate":
            write_generated_documents(project)
            print(
                json.dumps(
                    {"generated": sorted(GENERATED_DOCUMENTS)},
                    sort_keys=True,
                )
            )
            return 0
        if args.check_docs:
            check_generated_documents(project)
        print(
            json.dumps(
                {
                    "status": "valid",
                    "outcomes": len(project.outcomes),
                    "capabilities": len(project.capabilities),
                    "changes": len(project.changes),
                    "assets": len(project.assets),
                    "source_digest": project_source_digest(root),
                },
                sort_keys=True,
            )
        )
        return 0
    except ProjectModelError as error:
        parser.error(str(error))
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
