#!/usr/bin/env python3
"""Generate the dependency-free C++ view of the v1 golden vectors."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any


DEFAULT_MANIFEST = Path(__file__).with_name("vectors.json")
DEFAULT_OUTPUT = (
    Path(__file__).resolve().parents[3]
    / "native"
    / "tests"
    / "protocol"
    / "v1_golden_vectors.inc"
)

DIRECTIONS = {
    "initiator_to_responder": "Direction::kInitiatorToResponder",
    "responder_to_initiator": "Direction::kResponderToInitiator",
}


def cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def require_string(value: Any, context: str) -> str:
    if not isinstance(value, str):
        raise ValueError(f"{context} must be a string")
    return value


def render(manifest_path: Path) -> str:
    source = manifest_path.read_bytes()
    manifest = json.loads(source)
    if manifest.get("format_version") != 1:
        raise ValueError("unsupported vector manifest format")

    frames = manifest.get("frames")
    cases = manifest.get("cases")
    if not isinstance(frames, dict) or not isinstance(cases, list):
        raise ValueError("manifest frames/cases have the wrong type")

    frame_lines: list[str] = []
    for name, frame in frames.items():
        frame_name = require_string(name, "frame name")
        if not isinstance(frame, dict):
            raise ValueError(f"frame {frame_name!r} must be an object")
        direction = require_string(
            frame.get("direction"), f"frame {frame_name!r} direction"
        )
        if direction not in DIRECTIONS:
            raise ValueError(f"frame {frame_name!r} has an invalid direction")
        encoded = require_string(frame.get("hex"), f"frame {frame_name!r} hex")
        bytes.fromhex(encoded)
        frame_lines.append(
            "    GoldenFrame{"
            f"{cpp_string(frame_name)}, {DIRECTIONS[direction]}, "
            f"{cpp_string(encoded)}"
            "},"
        )

    maximum_frames = max((len(case.get("frames", [])) for case in cases), default=0)
    if maximum_frames == 0:
        raise ValueError("manifest has no case frames")

    case_lines: list[str] = []
    seen_names: set[str] = set()
    for case in cases:
        if not isinstance(case, dict):
            raise ValueError("case must be an object")
        name = require_string(case.get("name"), "case name")
        if not name or name in seen_names:
            raise ValueError(f"invalid or duplicate case name {name!r}")
        seen_names.add(name)

        frame_names = case.get("frames")
        expected = case.get("expect")
        if not isinstance(frame_names, list) or not isinstance(expected, dict):
            raise ValueError(f"case {name!r} has invalid frames/expect")
        rendered_names: list[str] = []
        for frame_name_value in frame_names:
            frame_name = require_string(
                frame_name_value, f"case {name!r} frame name"
            )
            if frame_name not in frames:
                raise ValueError(
                    f"case {name!r} references unknown frame {frame_name!r}"
                )
            rendered_names.append(cpp_string(frame_name))

        result = require_string(expected.get("result"), f"case {name!r} result")
        if result not in {"accept", "reject"}:
            raise ValueError(f"case {name!r} has invalid result {result!r}")
        error = ""
        if result == "reject":
            error = require_string(expected.get("error"), f"case {name!r} error")

        names_initializer = ", ".join(rendered_names)
        case_lines.append(
            "    GoldenCase{"
            f"{cpp_string(name)}, "
            f"{{{names_initializer}}}, {len(rendered_names)}, "
            f"{str(result == 'accept').lower()}, {cpp_string(error)}"
            "},"
        )

    digest = hashlib.sha256(source).hexdigest()
    return "\n".join(
        [
            "// Generated by protocol/testdata/v1/generate_native_vectors.py.",
            "// Do not edit by hand; run the generator or use --check for drift.",
            f'inline constexpr std::string_view kGoldenManifestSha256 = "{digest}";',
            "",
            f"inline constexpr std::array<GoldenFrame, {len(frame_lines)}> "
            "kGoldenFrames{",
            *frame_lines,
            "};",
            "",
            f"inline constexpr std::size_t kMaximumGoldenCaseFrames = "
            f"{maximum_frames};",
            f"inline constexpr std::array<GoldenCase, {len(case_lines)}> "
            "kGoldenCases{",
            *case_lines,
            "};",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the generated output differs instead of writing it",
    )
    args = parser.parse_args()

    try:
        generated = render(args.manifest)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"generation failed: {error}", file=sys.stderr)
        return 2

    if args.check:
        try:
            current = args.output.read_text(encoding="utf-8")
        except OSError as error:
            print(f"cannot read generated fixture: {error}", file=sys.stderr)
            return 1
        if current != generated:
            print(
                f"{args.output} is stale; run {Path(__file__).name}",
                file=sys.stderr,
            )
            return 1
        print(
            f"Native vector fixture matches {args.manifest} "
            f"(sha256 {hashlib.sha256(args.manifest.read_bytes()).hexdigest()})."
        )
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated, encoding="utf-8")
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
